# Turn on automatic reviewer choosing and assignment
addReviewers: true

# Automatic assign pull request to its author
addAssignees: author

# Set of available reviewers
reviewers:
  - ceskyDJ
  - KoubaFromPucks

# Limit of assigned reviewers
numberOfReviewers: 1
