name: 'Tests | Basic tests'

on: [push]

jobs:
  # Check rules from assignment
  assignment-rules:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Create directory for testing purposes
        run: mkdir tmp

      - name: Run own tests
        run: ./test/basics/other-assignment-rules.sh

