name: 'Automation | Pull request'

on:
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  # Assign pull request to its author and choose and set reviewer
  auto-assign-author-and-reviewer:
    if: ${{ github.event.action == 'opened' || github.event.action == 'ready_for_review' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          repo-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
